/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Ganindu Samarajeewa
 */
public class home1_house extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    JTable table; 
    DefaultTableModel model;
    int i;

    /**
     * Creates new form test
     */
    public home1_house() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        side_pane = new javax.swing.JPanel();
        btn_electorhhn4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_electorhhn1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_electorhhn5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_electorhhn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        side_pane1 = new javax.swing.JPanel();
        btn_electorhhn2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_electorhhn3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Householddata = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane.setBackground(new java.awt.Color(54, 33, 89));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_electorhhn4.setBackground(new java.awt.Color(84, 65, 118));
        btn_electorhhn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_electorhhn4MousePressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1/images/icons8_home_15px.png"))); // NOI18N

        jLabel11.setBackground(new java.awt.Color(64, 43, 100));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Electors House Hold Numbers");

        javax.swing.GroupLayout btn_electorhhn4Layout = new javax.swing.GroupLayout(btn_electorhhn4);
        btn_electorhhn4.setLayout(btn_electorhhn4Layout);
        btn_electorhhn4Layout.setHorizontalGroup(
            btn_electorhhn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_electorhhn4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
        btn_electorhhn4Layout.setVerticalGroup(
            btn_electorhhn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_electorhhn4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_electorhhn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap())
        );

        side_pane.add(btn_electorhhn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 330, 60));

        btn_electorhhn1.setBackground(new java.awt.Color(64, 43, 100));
        btn_electorhhn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_electorhhn1MousePressed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1/images/icons8_elections_15px.png"))); // NOI18N

        jLabel12.setBackground(new java.awt.Color(64, 43, 100));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("All Electors In Division");

        javax.swing.GroupLayout btn_electorhhn1Layout = new javax.swing.GroupLayout(btn_electorhhn1);
        btn_electorhhn1.setLayout(btn_electorhhn1Layout);
        btn_electorhhn1Layout.setHorizontalGroup(
            btn_electorhhn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_electorhhn1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        btn_electorhhn1Layout.setVerticalGroup(
            btn_electorhhn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_electorhhn1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_electorhhn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap())
        );

        side_pane.add(btn_electorhhn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 330, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1/images/sl.png"))); // NOI18N
        side_pane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 60, 380, 160));

        btn_electorhhn5.setBackground(new java.awt.Color(64, 43, 100));
        btn_electorhhn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_electorhhn5MousePressed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1/images/icons8_registration_15px.png"))); // NOI18N

        jLabel15.setBackground(new java.awt.Color(64, 43, 100));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("New Registerd Electors");

        javax.swing.GroupLayout btn_electorhhn5Layout = new javax.swing.GroupLayout(btn_electorhhn5);
        btn_electorhhn5.setLayout(btn_electorhhn5Layout);
        btn_electorhhn5Layout.setHorizontalGroup(
            btn_electorhhn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_electorhhn5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        btn_electorhhn5Layout.setVerticalGroup(
            btn_electorhhn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_electorhhn5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_electorhhn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap())
        );

        side_pane.add(btn_electorhhn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 330, 60));

        btn_electorhhn.setBackground(new java.awt.Color(64, 43, 100));
        btn_electorhhn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_electorhhnMousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1/images/icons8_menu_24px.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(64, 43, 100));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Home");

        javax.swing.GroupLayout btn_electorhhnLayout = new javax.swing.GroupLayout(btn_electorhhn);
        btn_electorhhn.setLayout(btn_electorhhnLayout);
        btn_electorhhnLayout.setHorizontalGroup(
            btn_electorhhnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_electorhhnLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_electorhhnLayout.setVerticalGroup(
            btn_electorhhnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_electorhhnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_electorhhnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        side_pane.add(btn_electorhhn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 330, 60));

        bg.add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 600));

        jPanel1.setBackground(new java.awt.Color(110, 89, 221));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ELECTORS HOUSE HOLD NUMBERS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(348, 348, 348))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 940, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "House Hold Number", "Grama Niladari Division", "Village/Street/State"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 810, 200));

        side_pane1.setBackground(new java.awt.Color(54, 33, 89));
        side_pane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_electorhhn2.setBackground(new java.awt.Color(64, 43, 100));

        jLabel8.setBackground(new java.awt.Color(64, 43, 100));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Electors House Hold Numbers");

        javax.swing.GroupLayout btn_electorhhn2Layout = new javax.swing.GroupLayout(btn_electorhhn2);
        btn_electorhhn2.setLayout(btn_electorhhn2Layout);
        btn_electorhhn2Layout.setHorizontalGroup(
            btn_electorhhn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_electorhhn2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_electorhhn2Layout.setVerticalGroup(
            btn_electorhhn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_electorhhn2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_electorhhn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap())
        );

        side_pane1.add(btn_electorhhn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 330, 60));

        btn_electorhhn3.setBackground(new java.awt.Color(84, 65, 118));
        btn_electorhhn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_electorhhn3MousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pro1/images/icons8_elections_15px.png"))); // NOI18N

        jLabel10.setBackground(new java.awt.Color(85, 65, 240));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("All Electors In Division");

        javax.swing.GroupLayout btn_electorhhn3Layout = new javax.swing.GroupLayout(btn_electorhhn3);
        btn_electorhhn3.setLayout(btn_electorhhn3Layout);
        btn_electorhhn3Layout.setHorizontalGroup(
            btn_electorhhn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_electorhhn3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_electorhhn3Layout.setVerticalGroup(
            btn_electorhhn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_electorhhn3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_electorhhn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap())
        );

        side_pane1.add(btn_electorhhn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 330, -1));

        bg.add(side_pane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 600));

        Householddata.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Householddata.setText("Show House Hold Data");
        Householddata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HouseholddataActionPerformed(evt);
            }
        });
        bg.add(Householddata, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 810, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_electorhhnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_electorhhnMousePressed
        // TODO add your handling code here:
        main nr = new  main();
        nr.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_electorhhnMousePressed

    private void btn_electorhhn4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_electorhhn4MousePressed
        // TODO add your handling code here:
        home1_house h1 = new home1_house();
        h1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_electorhhn4MousePressed

    private void btn_electorhhn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_electorhhn1MousePressed
         votediv ds = new votediv();
        ds.setVisible(true);
        dispose();
       
    }//GEN-LAST:event_btn_electorhhn1MousePressed

    private void btn_electorhhn3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_electorhhn3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_electorhhn3MousePressed

    private void btn_electorhhn5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_electorhhn5MousePressed
         newreg nr = new newreg();
        nr.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_electorhhn5MousePressed

    private void HouseholddataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HouseholddataActionPerformed
         try{
            model=(DefaultTableModel) jTable1.getModel();
            
            table=new JTable(model);
            

            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gramadb", "root", "");
            String query = "SELECT * FROM electoral_district_web";
            Statement st = con.createStatement();
            
            PreparedStatement pstmt1 = null;
            pstmt1 = con.prepareStatement(query);
            
            rs = pstmt1.executeQuery();
            Object[] row=new Object[13];
            int r=0;
            int c=0;
            int rn=1;
            while(rs.next()){
               
                model.setRowCount(rn);
                table.setValueAt(rs.getString("Grama_Niladhari_Division_"),r,c);
                table.setValueAt(rs.getString("Village_Street_or_Estate"),r,c+1);
                table.setValueAt(rs.getInt("Household_Number"),r,c+2);
                

                r++;
                rn++;
                c=0;
           }
        }
           catch(Exception ex){
           
                JOptionPane.showMessageDialog(null, ex);
           }
    }//GEN-LAST:event_HouseholddataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home1_house.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home1_house.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home1_house.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home1_house.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home1_house().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Householddata;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btn_electorhhn;
    private javax.swing.JPanel btn_electorhhn1;
    private javax.swing.JPanel btn_electorhhn2;
    private javax.swing.JPanel btn_electorhhn3;
    private javax.swing.JPanel btn_electorhhn4;
    private javax.swing.JPanel btn_electorhhn5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel side_pane;
    private javax.swing.JPanel side_pane1;
    // End of variables declaration//GEN-END:variables
}
