/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import Logins.maindetails;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.awt.HeadlessException;
import java.sql.Statement;
import java.awt.event.MouseEvent;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Oshika Imashanee
 */
public class otheroption extends javax.swing.JFrame {
    
    Connection con = null; 
    PreparedStatement pst = null;
    ResultSet rs = null;
    JTable table; 
    DefaultTableModel model;
    int i;

    /**
     * Creates new form otheroption
     */
    public otheroption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jFrame1 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblgramaniladharidivisionnumb = new javax.swing.JLabel();
        lblgramaniladharidivision = new javax.swing.JLabel();
        lblpollingdivision = new javax.swing.JLabel();
        lblpollingdistrict = new javax.swing.JLabel();
        lblelectoraldistrict = new javax.swing.JLabel();
        txtgramaniladharidivisionnumb = new javax.swing.JTextField();
        txtgramaniladharidivision = new javax.swing.JTextField();
        txtpollingdivision = new javax.swing.JTextField();
        txtpollingdistrict = new javax.swing.JTextField();
        txtelectoraldistrict = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        electiontable = new javax.swing.JTable();
        btndelete = new javax.swing.JToggleButton();
        btnupdate = new javax.swing.JToggleButton();
        btnadd = new javax.swing.JToggleButton();
        btnget = new javax.swing.JToggleButton();
        btnview = new javax.swing.JToggleButton();
        btnclear = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblgramaniladharidivisionnumb1 = new javax.swing.JLabel();
        lblgramaniladharidivision1 = new javax.swing.JLabel();
        lblpollingdivision1 = new javax.swing.JLabel();
        lblpollingdistrict1 = new javax.swing.JLabel();
        lblelectoraldistrict1 = new javax.swing.JLabel();
        divno = new javax.swing.JTextField();
        div = new javax.swing.JTextField();
        pdivno = new javax.swing.JTextField();
        pdiv = new javax.swing.JTextField();
        edis = new javax.swing.JTextField();
        lblelectoraldistrict2 = new javax.swing.JLabel();
        vill = new javax.swing.JTextField();
        lblelectoraldistrict3 = new javax.swing.JLabel();
        holdno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        btndelete1 = new javax.swing.JToggleButton();
        btnupdate1 = new javax.swing.JToggleButton();
        btnadd1 = new javax.swing.JToggleButton();
        btnget1 = new javax.swing.JToggleButton();
        btnview1 = new javax.swing.JToggleButton();
        btnclear1 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jToggleButton1.setText("jToggleButton1");

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setText("RESET  DETAILS");

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        lblgramaniladharidivisionnumb.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblgramaniladharidivisionnumb.setText("Grama Niladhari Division Number");

        lblgramaniladharidivision.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblgramaniladharidivision.setText("Grama Niladhari Division");

        lblpollingdivision.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblpollingdivision.setText("Polling  Division");

        lblpollingdistrict.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblpollingdistrict.setText("Polling District");

        lblelectoraldistrict.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblelectoraldistrict.setText("Electoral District");

        txtgramaniladharidivisionnumb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtgramaniladharidivision.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtpollingdivision.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtpollingdistrict.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtelectoraldistrict.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblgramaniladharidivisionnumb)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtgramaniladharidivisionnumb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtpollingdivision, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtpollingdistrict, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtelectoraldistrict, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblpollingdivision)
                            .addComponent(lblpollingdistrict)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblgramaniladharidivision)
                            .addComponent(txtgramaniladharidivision, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblelectoraldistrict)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblgramaniladharidivisionnumb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtgramaniladharidivisionnumb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblgramaniladharidivision)
                .addGap(18, 18, 18)
                .addComponent(txtgramaniladharidivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(lblpollingdivision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpollingdivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblpollingdistrict)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtpollingdistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblelectoraldistrict)
                .addGap(23, 23, 23)
                .addComponent(txtelectoraldistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logins/logo.png"))); // NOI18N
        jToggleButton5.setText("jToggleButton5");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logins/backarrow.jpg"))); // NOI18N
        jToggleButton7.setText("jToggleButton7");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        electiontable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "GN Division Nmb", "GN Division  ", "Polling Division", "Polling District", "Electoral District"
            }
        ));
        jScrollPane1.setViewportView(electiontable);

        btndelete.setBackground(new java.awt.Color(0, 51, 153));
        btndelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(0, 51, 153));
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnadd.setBackground(new java.awt.Color(0, 51, 153));
        btnadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnget.setBackground(new java.awt.Color(0, 51, 153));
        btnget.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnget.setForeground(new java.awt.Color(255, 255, 255));
        btnget.setText("Get Data");
        btnget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngetActionPerformed(evt);
            }
        });

        btnview.setBackground(new java.awt.Color(0, 51, 153));
        btnview.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnview.setForeground(new java.awt.Color(255, 255, 255));
        btnview.setText("View");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(0, 51, 153));
        btnclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(255, 255, 255));
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnget, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnview, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnupdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217)
                        .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(348, 348, 348)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnget, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnview, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 55)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setText("ELECTION  2021");

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        lblgramaniladharidivisionnumb1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblgramaniladharidivisionnumb1.setText("Grama Niladhari Division Number");

        lblgramaniladharidivision1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblgramaniladharidivision1.setText("Grama Niladhari Division");

        lblpollingdivision1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblpollingdivision1.setText("Polling  Division Number");

        lblpollingdistrict1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblpollingdistrict1.setText("Polling Division");

        lblelectoraldistrict1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblelectoraldistrict1.setText("Electoral District");

        divno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        div.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pdivno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pdiv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        edis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblelectoraldistrict2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblelectoraldistrict2.setText("Village or Estate or Street");

        vill.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblelectoraldistrict3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblelectoraldistrict3.setText("Household_Number");

        holdno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setText("Don't change this value when you updating");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblgramaniladharidivision1)
                        .addGap(158, 158, 158))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpollingdivision1)
                            .addComponent(pdivno, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpollingdistrict1)
                            .addComponent(pdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblelectoraldistrict1)
                            .addComponent(edis, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblelectoraldistrict2)
                            .addComponent(vill, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblelectoraldistrict3)
                            .addComponent(holdno, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(divno, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblgramaniladharidivisionnumb1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblgramaniladharidivisionnumb1)
                .addGap(11, 11, 11)
                .addComponent(divno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblgramaniladharidivision1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblpollingdivision1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pdivno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(lblpollingdistrict1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pdiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lblelectoraldistrict1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblelectoraldistrict2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblelectoraldistrict3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(holdno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logins/logo.png"))); // NOI18N
        jToggleButton6.setText("jToggleButton5");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logins/backarrow.jpg"))); // NOI18N
        jToggleButton8.setText("jToggleButton7");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        btndelete1.setBackground(new java.awt.Color(0, 51, 153));
        btndelete1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndelete1.setForeground(new java.awt.Color(255, 255, 255));
        btndelete1.setText("DELETE");
        btndelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete1ActionPerformed(evt);
            }
        });

        btnupdate1.setBackground(new java.awt.Color(0, 51, 153));
        btnupdate1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnupdate1.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate1.setText("UPDATE");
        btnupdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate1ActionPerformed(evt);
            }
        });

        btnadd1.setBackground(new java.awt.Color(0, 51, 153));
        btnadd1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnadd1.setForeground(new java.awt.Color(255, 255, 255));
        btnadd1.setText("Add");
        btnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd1ActionPerformed(evt);
            }
        });

        btnget1.setBackground(new java.awt.Color(0, 51, 153));
        btnget1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnget1.setForeground(new java.awt.Color(255, 255, 255));
        btnget1.setText("Get Data");
        btnget1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnget1ActionPerformed(evt);
            }
        });

        btnview1.setBackground(new java.awt.Color(0, 51, 153));
        btnview1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnview1.setForeground(new java.awt.Color(255, 255, 255));
        btnview1.setText("View");
        btnview1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnview1ActionPerformed(evt);
            }
        });

        btnclear1.setBackground(new java.awt.Color(0, 51, 153));
        btnclear1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnclear1.setForeground(new java.awt.Color(255, 255, 255));
        btnclear1.setText("Clear");
        btnclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclear1ActionPerformed(evt);
            }
        });

        jTable2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "GN Division Nmb", "GN Division", "Polling Division", "Polling Division Number", "Electroral District", "Village Street or Estate", "Household Number"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnget1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnview1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnclear1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnadd1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnupdate1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217)
                        .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnget1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnview1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnupdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnadd1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnclear1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        maindetails b = new maindetails();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel) electiontable.getModel();
        if(electiontable.getSelectedRow()==1){
            if(electiontable.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty");
            }else{
                JOptionPane.showMessageDialog(this,"Please select single Row for Delete");
            }
        }
        else{
            tblModel.removeRow(electiontable.getSelectedRow());
        }

    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed

        try{

            String value1= txtgramaniladharidivisionnumb.getText();
            String value2= txtgramaniladharidivision.getText();
            String value3= txtpollingdivision.getText();
            String value4= txtpollingdistrict.getText();
            String value5= txtelectoraldistrict.getText();

            String sql="UPDATE `electoral_district` SET `GNdivisionnmb`='"+value1+"',`GNDivision`='"+value2+"',`pollingdivision`='"+value3+"',`pollingdistrictnmb`='"+value4+"',`electoraldistrict`='"+value5+"' where `GNdivisionnmb`='"+value1+"' ";
            pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Updated Successfully");

        }

        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed

        try {

            String sql ="INSERT INTO `electoral_district`"
            +"(`GNdivisionnmb`, `GNDivision`, `pollingdivision`,`pollingdistrictnmb`,`electoraldistrict`)"
            +" VALUES (?,?,?,?,?)";

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ip","root","");

            pst = con.prepareStatement(sql);
            pst.setString(1,txtgramaniladharidivisionnumb.getText());
            pst.setString(2,txtgramaniladharidivision.getText());
            pst.setString(3,txtpollingdivision.getText());
            pst.setString(4,txtpollingdistrict.getText());
            pst.setString(5,txtelectoraldistrict.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted Successfully!");

        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btngetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngetActionPerformed
        try{

            model = (DefaultTableModel) electiontable.getModel();

            table = new JTable(model);

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gramadb","root","");
            String query = "SELECT * FROM electoral_district";
            Statement st2 = con.createStatement();

            PreparedStatement pst2 = null;
            pst2 = con.prepareStatement(query);
            rs = pst2.executeQuery();

            Object[] row = new Object[6];

            int r=0;
            int c=0;
            int rn=1;

            while(rs.next()){

                model.setRowCount(rn);
                table.setValueAt(rs.getString("GNdivisionnmb"),r,c);
                table.setValueAt(rs.getString("GNDivision"),r,c+1);
                table.setValueAt(rs.getString("pollingdivision"),r,c+2);
                table.setValueAt(rs.getString("pollingdistrictnmb"),r,c+3);
                table.setValueAt(rs.getString("electoraldistrict"),r,c+4);

                r++;
                rn++;
                c=0;
            }
        }

        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btngetActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        int i2 = electiontable.getSelectedRow();
        txtgramaniladharidivisionnumb.setText(table.getValueAt(i2,0).toString());
        txtgramaniladharidivision.setText((String) table.getValueAt(i2,1));
        txtpollingdivision.setText((String) table.getValueAt(i2,2));
        txtpollingdistrict.setText((String) table.getValueAt(i2,3));
        txtelectoraldistrict.setText((String) table.getValueAt(i2,4));
    }//GEN-LAST:event_btnviewActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtgramaniladharidivisionnumb.setText(null);
        txtpollingdistrict.setText(null);
        txtgramaniladharidivision.setText(null);
        txtpollingdivision.setText(null);
        txtelectoraldistrict.setText(null);
    }//GEN-LAST:event_btnclearActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        test2 b = new test2();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void btndelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete1ActionPerformed
        int i2 = jTable2.getSelectedRow();
        String value7=(String) jTable2.getValueAt(i2,6);
        
        
        DefaultTableModel tblModel = (DefaultTableModel) jTable2.getModel();
        if(jTable2.getSelectedRow()==1){
            if(jTable2.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty");
            }else{
                JOptionPane.showMessageDialog(this,"Please select single Row for Delete");
            }
        }
        else{
            tblModel.removeRow(jTable2.getSelectedRow());
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/grama_niladhari","root","");
            String query = "DELETE FROM `electoral_district` WHERE `Household_Number`=?";
            pst = con.prepareStatement(query);
            pst.setString(1,value7);
            pst.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(otheroption.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_btndelete1ActionPerformed

    private void btnupdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate1ActionPerformed

        try{

            String value1= divno.getText();
            String value2= div.getText();
            String value3= pdivno.getText();
            String value4= pdiv.getText();
            String value5= edis.getText();
            String value6= vill.getText();
            String value7= holdno.getText();
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/grama_niladhari", "root", "");
            String sql="UPDATE `electoral_district` SET `Grama_Niladari_Division_Num`='"+value1+"',`Grama_Niladhari_Division`='"+value2+"',`Polling_District_Num`='"+value3+"',`Polling_Division`='"+value4+"',`Electoral_District`='"+value5+"',`Village_Street_or_Estate`='"+value6+"' where `Household_Number`='"+value7+"' ";
            pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Updated Successfully");

        }

        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_btnupdate1ActionPerformed

    private void btnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd1ActionPerformed

        try {

            String sql ="INSERT INTO `electoral_district`"
            +"(`Grama_Niladari_Division_Num`, `Grama_Niladhari_Division`, `Polling_Division`,`Polling_District_Num`,`Electoral_District`,`Village_Street_or_Estate`,`Household_Number`)"
            +" VALUES (?,?,?,?,?,?,?)";

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/grama_niladhari","root","");

            pst = con.prepareStatement(sql);
            pst.setString(1,divno.getText());
            pst.setString(2,div.getText());
            pst.setString(3,pdiv.getText());
            pst.setString(4,pdivno.getText());
            pst.setString(5,edis.getText());
            pst.setString(6,vill.getText());
            pst.setString(7,holdno.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted Successfully!");

        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_btnadd1ActionPerformed

    private void btnget1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnget1ActionPerformed
        try{
            model=(DefaultTableModel) jTable2.getModel();
            
            table=new JTable(model);
            

            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/grama_niladhari", "root", "");
            String query = "SELECT * FROM electoral_district";
            Statement st = con.createStatement();
            
            PreparedStatement pstmt1 = null;
            pstmt1 = con.prepareStatement(query);
            
            rs = pstmt1.executeQuery();
            Object[] row = new Object[13];
            int r=0;
            int c=0;
            int rn=1;
            while(rs.next()){
               
                model.setRowCount(rn);
                table.setValueAt(rs.getString("Grama_Niladari_Division_Num"),r,c);
                table.setValueAt(rs.getString("Grama_Niladhari_Division"),r,c+1);
                table.setValueAt(rs.getString("Polling_Division"),r,c+2);
                table.setValueAt(rs.getString("Polling_District_Num"),r,c+3);
                table.setValueAt(rs.getString("Electoral_District"),r,c+4);
                table.setValueAt(rs.getString("Village_Street_or_Estate"),r,c+5);
                table.setValueAt(rs.getString("Household_Number"),r,c+6);
                

                r++;
                rn++;
                c=0;
           }
        }
        catch(Exception ex){

             JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnget1ActionPerformed

    private void btnview1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnview1ActionPerformed
        int i2 = jTable2.getSelectedRow();
        divno.setText(table.getValueAt(i2,0).toString());
        div.setText((String) table.getValueAt(i2,1));
        pdivno.setText((String) table.getValueAt(i2,2));
        pdiv.setText((String) table.getValueAt(i2,3));
        edis.setText((String) table.getValueAt(i2,4));
        vill.setText((String) table.getValueAt(i2,5));
        holdno.setText((String) table.getValueAt(i2,6));
    }//GEN-LAST:event_btnview1ActionPerformed

    private void btnclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclear1ActionPerformed
        divno.setText("");
        div.setText("");
        pdivno.setText("");
        pdiv.setText("");
        edis.setText("");
        vill.setText("");
        holdno.setText("");
    }//GEN-LAST:event_btnclear1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(otheroption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(otheroption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(otheroption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(otheroption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new otheroption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnadd;
    private javax.swing.JToggleButton btnadd1;
    private javax.swing.JToggleButton btnclear;
    private javax.swing.JToggleButton btnclear1;
    private javax.swing.JToggleButton btndelete;
    private javax.swing.JToggleButton btndelete1;
    private javax.swing.JToggleButton btnget;
    private javax.swing.JToggleButton btnget1;
    private javax.swing.JToggleButton btnupdate;
    private javax.swing.JToggleButton btnupdate1;
    private javax.swing.JToggleButton btnview;
    private javax.swing.JToggleButton btnview1;
    private javax.swing.JTextField div;
    private javax.swing.JTextField divno;
    private javax.swing.JTextField edis;
    private javax.swing.JTable electiontable;
    private javax.swing.JTextField holdno;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JLabel lblelectoraldistrict;
    private javax.swing.JLabel lblelectoraldistrict1;
    private javax.swing.JLabel lblelectoraldistrict2;
    private javax.swing.JLabel lblelectoraldistrict3;
    private javax.swing.JLabel lblgramaniladharidivision;
    private javax.swing.JLabel lblgramaniladharidivision1;
    private javax.swing.JLabel lblgramaniladharidivisionnumb;
    private javax.swing.JLabel lblgramaniladharidivisionnumb1;
    private javax.swing.JLabel lblpollingdistrict;
    private javax.swing.JLabel lblpollingdistrict1;
    private javax.swing.JLabel lblpollingdivision;
    private javax.swing.JLabel lblpollingdivision1;
    private javax.swing.JTextField pdiv;
    private javax.swing.JTextField pdivno;
    private javax.swing.JTextField txtelectoraldistrict;
    private javax.swing.JTextField txtgramaniladharidivision;
    private javax.swing.JTextField txtgramaniladharidivisionnumb;
    private javax.swing.JTextField txtpollingdistrict;
    private javax.swing.JTextField txtpollingdivision;
    private javax.swing.JTextField vill;
    // End of variables declaration//GEN-END:variables
}
